### ISSUE TITLE
Add index signature to the generated interface

### ISSUE THREAD

**Issue by unstubbable** [Jimdo/typings-for-css-modules-plugin#10]
See http://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types, e.g. (see line 2):

``` typescript
export interface IMyComponentScss {
  [className: string]: string;
  'some-class': string;
  'someOtherClass': string;
  'some-class-sayWhat': string;
}
declare const styles: IMyComponentScss;

export default styles;
```

Then it would be possible to access a style with a dynamic class name, e.g.:

``` typescript
import styles from './myComponent.scss';

const activeClass = styles[`foo-${this.props.active}`];
```

**Comment by unstubbable** [comment]
You could also make an option for this.

**Comment by timse** [comment]
Please consider using `suppressImplicitAnyIndexErrors` as adding the index signature kills the ability to check for actually existing classes.

**Comment by unstubbable** [comment]
You're right, this is a better solution and solves this issue in other parts of our project as well.
