### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by fenech** [Jimdo/typings-for-css-modules-plugin#11]
I have added the following lines to my `webpack.config.js`:

```
const TypingsPlugin = require("typings-for-css-modules-plugin");

module.exports = {
    // ...
    plugins: [
        new ExtractTextPlugin('styles.css'),
        new TypingsPlugin({
            verbose: false
        })
    ]
};
```

When I try to run webpack, I get the following error:

```
tom@localhost myProject]$ npm run webpack

> my-project@0.0.1 webpack /home/tom/dev/myProject
> webpack --progress --colors --watch

/home/tom/dev/myProject/node_modules/typings-for-css-modules-plugin/lib/index.js:51
      var ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(compilation, mod) {
                                  ^

ReferenceError: regeneratorRuntime is not defined
    at /home/tom/dev/myProject/node_modules/typings-for-css-modules-plugin/lib/index.js:51:35
    at /home/tom/dev/myProject/node_modules/typings-for-css-modules-plugin/lib/index.js:79:6
    at Object.<anonymous> (/home/tom/dev/myProject/node_modules/typings-for-css-modules-plugin/lib/index.js:437:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/tom/dev/myProject/webpack.config.js:3:23)
```

Does this plugin have a dependency on something else that I am perhaps missing?

**Comment by mattoni** [comment]
I'm having the same issue, did you figure out a workaround?

**Comment by fenech** [comment]
Unfortunately, my current workaround is not to use typings for CSS modules!

**Comment by fenech** [comment]
@AlexanderMattoni  I managed to get the definitions to build by installing `babel-polyfill` and adding these lines to my webpack config:

```
import "babel-polyfill";
import TypingsPlugin from "typings-for-css-modules-plugin";
```

In order to use `import` in my webpack config, I had to do some extra messing around.

I renamed the webpack config file to `webpack.config.babel.js` and created the file `.babelrc` with the following contents:

```
{
    "presets": ["es2015"]
}
```

My `package.json` now contains the following babel-related dev dependencies:

```
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.13.2",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-register": "^6.11.6",
```

...so if you're missing any of them, I'd suggest installing them using `npm install <package> --save-dev`.

**Comment by timse** [comment]
Hey guys, sorry for responding so late, I will look into this!

All those workarounds should not be necessary, sorry for this!

**Comment by mattoni** [comment]
I see this was merged in 13 days ago, any chance on a fresh npm version soon?

**Comment by timse** [comment]
done :) i would close this then!
