### ISSUE TITLE
TypingsForCssModulesPlugin - No CSS Module found. Skip typings extraction...

### ISSUE THREAD

**Issue by danroberts** [Jimdo/typings-for-css-modules-plugin#13]
I might have something configured wrong in my setup... but I have a css file that I'm importing in my .tsx component, but running webpack gives me that message.

Is there any way you could provide an example webpack config or project?

**Comment by danroberts** [comment]
I see, this happens because the first time webpack is run, there are no .d.ts typings, so the import statement doesn't resolve, thereby making webpack not able to find the .css. You can get around this by creating the .d.ts file by hand for the first time.

**Comment by timse** [comment]
yes, this is a known issue, im trying to find a way to not have to do this (create a d.ts file by hand/restart webpack) any ideas are very welcome :).

Also I should put this into the Readme!

**Comment by timse** [comment]
Hey sorry for my late reply, but I was checking all the issues that occured and went for a very different solution by rewriting the plugin to be a drop in replacement for the css-loader, see here: https://github.com/Jimdo/typings-for-css-modules-loader.

I will therefore close this issue and hope you give the loader a try :)!
