### ISSUE TITLE
Plugin assumes default export

### ISSUE THREAD

**Issue by mattoni** [Jimdo/typings-for-css-modules-plugin#17]
The extract-text plugin for webpack doesn't replace the css with default exports, instead it just does 'modules.exports'. In all the examples you do `import styles from "styles.css"`, is there any way to make them work together? I modified the extract text plugin to do modules.export.default but that's not a good long term solution.

**Comment by timse** [comment]
Hey sorry for my late reply, but I was checking all the issues that occured and went for a very different solution by rewriting the plugin to be a drop in replacement for the css-loader, see here: https://github.com/Jimdo/typings-for-css-modules-loader.

I will therefore close this issue and hope you give the loader a try :)!
