### ISSUE TITLE
broken release 0.0.4

### ISSUE THREAD

**Issue by unstubbable** [Jimdo/typings-for-css-modules-plugin#9]
The published artifact for `typings-for-css-modules-plugin@0.0.4` does not contain the `lib` directory.

**Comment by timse** [comment]
looking into it.

Do you mean the installed package from `npm` or just the release here on `github`?

**Comment by unstubbable** [comment]
I’m talking about the content in `node_modules/typings-for-css-modules-plugin` after `npm install`.

**Comment by timse** [comment]
should be fixed with https://github.com/Jimdo/typings-for-css-modules-plugin/commit/7ccc48ee527a0c03c1dcf447c694d2a69c1d7a1f
